"""
test_generic_table_column_order.py
----------------------------------
Test suite validating the mandatory generic table column order envelope
for every table generated by the DDL/schema generation process.

MANDATORY ENVELOPE REQUIREMENTS:
FIRST:
  1. ctrl_id int4 NULL
  2. exec_seq int4 NULL
  3. execution_date date NULL
  4. execution_schedule varchar(100) NULL

THEN:
  5+. All remaining columns from the source/business mapping.

LAST:
  - create_dtm timestamp DEFAULT now() NULL
  - update_dtm timestamp DEFAULT now() NULL
  - updated_by varchar(50) NULL
  - processing_date date NULL

CRITICAL CONSTRAINTS:
- ctrl_id MUST be the first column.
- exec_seq MUST be the second column.
- execution_date MUST be the third column.
- execution_schedule MUST be the fourth column.
- "id" is NOT a generic required column and must NOT be added automatically.
- Source/business columns must remain in the middle.
- The 4 audit/processing columns must always be the final 4 columns in exactly this order.
- No duplication if envelope columns already exist in source mapping.
- Source columns must not be dropped.
- Source columns must not be invented.
- Generic across all tables and controls.
"""

import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from target_logic_builder import (
    generate_source_tables_ddl,
    generate_target_ddl,
    build_table_columns_with_standard_envelope,
    _parse_required_objects_from_ddl,
)

FIRST_4_EXPECTED = [
    "ctrl_id",
    "exec_seq",
    "execution_date",
    "execution_schedule",
]

LAST_4_EXPECTED = [
    "create_dtm",
    "update_dtm",
    "updated_by",
    "processing_date",
]


def _assert_standard_envelope(table_name: str, columns: list[dict], expected_middle: list[str] = None):
    col_names = [c["name"].lower() for c in columns]
    assert len(col_names) >= 8, f"[{table_name}] Table has fewer than 8 columns: {col_names}"

    # 1. First 4 columns
    first_4 = col_names[:4]
    assert first_4 == FIRST_4_EXPECTED, (
        f"[{table_name}] First 4 columns mismatch.\n"
        f"Expected: {FIRST_4_EXPECTED}\n"
        f"Actual:   {first_4}"
    )

    # 2. Critical ordering: ctrl_id is first, exec_seq is second
    assert col_names[0] == "ctrl_id", f"[{table_name}] ctrl_id is not column 0 (got {col_names[0]})"
    assert col_names[1] == "exec_seq", f"[{table_name}] exec_seq is not column 1 (got {col_names[1]})"
    assert col_names[2] == "execution_date", f"[{table_name}] execution_date is not column 2 (got {col_names[2]})"
    assert col_names[3] == "execution_schedule", f"[{table_name}] execution_schedule is not column 3 (got {col_names[3]})"

    # 3. Last 4 columns
    last_4 = col_names[-4:]
    assert last_4 == LAST_4_EXPECTED, (
        f"[{table_name}] Last 4 columns mismatch.\n"
        f"Expected: {LAST_4_EXPECTED}\n"
        f"Actual:   {last_4}"
    )

    # 4. Middle columns check if provided
    middle_names = col_names[4:-4]
    if expected_middle is not None:
        assert middle_names == [m.lower() for m in expected_middle], (
            f"[{table_name}] Middle columns mismatch.\n"
            f"Expected: {expected_middle}\n"
            f"Actual:   {middle_names}"
        )

    # 5. Zero duplicate envelope columns
    for env_col in FIRST_4_EXPECTED + LAST_4_EXPECTED:
        count = col_names.count(env_col)
        assert count == 1, (
            f"[{table_name}] Column '{env_col}' appears {count} times (expected exactly 1). All cols: {col_names}"
        )


def test_helper_standard_envelope_direct():
    """Test build_table_columns_with_standard_envelope directly."""
    mid_cols = [
        "    customer_code VARCHAR(50) NOT NULL",
        "    balance_amt NUMERIC(18,2)",
        "    status_flag VARCHAR(10) DEFAULT 'ACTIVE'",
    ]
    res = build_table_columns_with_standard_envelope(mid_cols, target_dialect="postgresql")
    body = ",\n".join(res)
    ddl = f"CREATE TABLE test_schema.test_tbl (\n{body}\n);"
    parsed = _parse_required_objects_from_ddl(ddl)
    assert len(parsed) == 1
    _assert_standard_envelope("test_tbl", parsed[0]["columns"], ["customer_code", "balance_amt", "status_flag"])
    print("TEST 1 PASS - Direct helper produces exact 4-prefix, middle, and 4-suffix column envelope")


def test_helper_deduplication_of_existing_envelope_columns():
    """Test that existing envelope columns in source columns are never duplicated in the middle."""
    mid_cols = [
        "    ctrl_id INT",
        "    exec_seq INT",
        "    account_id VARCHAR(50)",
        "    create_dtm TIMESTAMP",
        "    updated_by VARCHAR(50)",
        "    processing_date DATE",
    ]
    res = build_table_columns_with_standard_envelope(mid_cols, target_dialect="postgresql")
    body = ",\n".join(res)
    ddl = f"CREATE TABLE test_schema.dedup_tbl (\n{body}\n);"
    parsed = _parse_required_objects_from_ddl(ddl)
    assert len(parsed) == 1
    _assert_standard_envelope("dedup_tbl", parsed[0]["columns"], ["account_id"])
    print("TEST 2 PASS - Existing envelope columns in source columns are deduplicated cleanly")


def test_replicated_source_tables_ddl():
    """Test generate_source_tables_ddl outputs standard envelope."""
    sources = [{"source_table": "raw_orders", "source_system": "sys_oms"}]
    introspect = {
        "raw_orders": {
            "table_found": True,
            "found_in_db": "PostgreSQL",
            "columns": [
                {"column_name": "order_id", "data_type": "VARCHAR(50)"},
                {"column_name": "order_amount", "data_type": "NUMERIC(12,2)"},
                {"column_name": "order_date", "data_type": "DATE"},
            ],
        }
    }
    analysis = {
        "rules": {
            "filter_rules": [
                {"data_stream": "raw_orders", "rule_statement": "Filter (order_id, order_amount, order_date)"}
            ]
        }
    }
    ddl = generate_source_tables_ddl("ra_ctrl.ctrl_01", "postgresql", sources, introspect, analysis)
    parsed = _parse_required_objects_from_ddl(ddl)
    assert len(parsed) == 1
    _assert_standard_envelope("raw_orders", parsed[0]["columns"], ["order_id", "order_amount", "order_date"])
    print("TEST 3 PASS - Replicated source table DDL conforms to generic column envelope")


def test_all_target_ddl_tables():
    """Test that every table produced by generate_target_ddl conforms to the envelope."""
    mock_sources = [{"source_table": "feed_alpha", "source_system": "sys_alpha"}]
    mock_introspect = {
        "feed_alpha": {
            "table_found": True,
            "found_in_db": "PostgreSQL",
            "columns": [
                {"column_name": "txn_id", "data_type": "VARCHAR(64)"},
                {"column_name": "txn_amt", "data_type": "NUMERIC(18,2)"},
            ],
        }
    }
    mock_rules = {
        "filter_rules": [
            {"data_stream": "feed_alpha", "rule_statement": "Filter (txn_id, txn_amt)"}
        ]
    }
    mock_mappings = [
        {"target_column": "report_client_id", "report_table_name": "rep_management_summary"},
        {"target_column": "report_balance", "report_table_name": "rep_management_summary"},
    ]
    mock_analysis = {
        "control_overview": {"identification": {"control_number": "CTRL-88"}},
        "rules": mock_rules,
        "config_tables": [
            {"config_table_name": "cfg_threshold_limits", "target_column": "threshold_limit"}
        ],
        "data_model": [
            {"table_name": "dm_calc_stage_tbl", "stage": "Calc", "load_type": "Truncate & load"}
        ],
    }

    ddl = generate_target_ddl(
        "ra_ctrl.ctrl_88",
        "postgresql",
        mock_sources,
        mock_rules,
        mock_mappings,
        mock_introspect,
        mock_analysis,
    )
    parsed_tables = _parse_required_objects_from_ddl(ddl)
    assert len(parsed_tables) >= 7, f"Expected at least 7 generated tables, got {len(parsed_tables)}"

    table_names = [t["bare_name"] for t in parsed_tables]
    print(f"Verified generated tables: {table_names}")

    for t in parsed_tables:
        _assert_standard_envelope(t["bare_name"], t["columns"])

    print("TEST 4 PASS - All generated table types in generate_target_ddl conform strictly to envelope")


def test_cross_control_generality():
    """Verify that multiple distinct controls (CTRL-05, CTRL-23, CTRL-99) all enforce generic envelope."""
    controls = ["CTRL-05", "CTRL-23", "CTRL-99", "CTRL-CUSTOM"]
    for c_num in controls:
        mock_analysis = {
            "control_overview": {"identification": {"control_number": c_num}},
            "config_tables": [{"config_table_name": "cfg_control_params", "target_column": "param_val"}],
        }
        mock_sources = [{"source_table": "src_events", "source_system": "sys_ev"}]
        mock_introspect = {
            "src_events": {
                "table_found": True,
                "found_in_db": "PostgreSQL",
                "columns": [{"column_name": "event_code", "data_type": "VARCHAR(30)"}],
            }
        }
        mock_rules = {
            "filter_rules": [{"data_stream": "src_events", "rule_statement": "Filter (event_code)"}]
        }
        ddl = generate_target_ddl(
            f"ra_ctrl.{c_num.lower()}",
            "postgresql",
            mock_sources,
            mock_rules,
            [],
            mock_introspect,
            mock_analysis,
        )
        parsed = _parse_required_objects_from_ddl(ddl)
        for t in parsed:
            _assert_standard_envelope(f"{c_num}:{t['bare_name']}", t["columns"])

    print("TEST 5 PASS - Generality verified across multiple controls without hardcoded assumptions")


def test_exact_sql_snippet_structure():
    """Verify the exact SQL string for the 4 initial columns and 4 final columns."""
    res = build_table_columns_with_standard_envelope(["    my_col VARCHAR(50)"], target_dialect="postgresql")
    ddl_block = ",\n".join(res)

    # Check exact keywords from user specification:
    assert "ctrl_id int4 NULL" in ddl_block
    assert "exec_seq int4 NULL" in ddl_block
    assert "execution_date date NULL" in ddl_block
    assert "execution_schedule varchar(100) NULL" in ddl_block
    assert "create_dtm timestamp DEFAULT now() NULL" in ddl_block
    assert "update_dtm timestamp DEFAULT now() NULL" in ddl_block
    assert "updated_by varchar(50) NULL" in ddl_block
    assert "processing_date date NULL" in ddl_block

    # Assert no automatic id column
    assert "\n    id " not in ddl_block
    assert "\n    id int4" not in ddl_block
    assert "GENERATED BY DEFAULT AS IDENTITY" not in ddl_block

    print("TEST 6 PASS - Exact SQL structure matches user specification (4-prefix and 4-suffix without id)")


if __name__ == "__main__":
    test_helper_standard_envelope_direct()
    test_helper_deduplication_of_existing_envelope_columns()
    test_replicated_source_tables_ddl()
    test_all_target_ddl_tables()
    test_cross_control_generality()
    test_exact_sql_snippet_structure()
    print("\n==================================================")
    print("All generic table column order tests PASSED (6/6)!")
    print("==================================================")
