"""
Tests for the generic idempotent deployment engine (post-fix).
Covers: parser correctness, generated/identity columns, constraint filtering,
nested parens, ALTER isolation, idempotency, and cross-control generality.

Run:
    python tests/test_idempotent_deploy.py
or:
    python -m pytest tests/test_idempotent_deploy.py -v
"""
import sys, os, re
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from target_logic_builder import (
    _split_top_level_defs,
    _parse_required_objects_from_ddl,
    _are_types_compatible,
    _build_alter_statements,
    _is_alter_safe,
    reconcile_objects,
    idempotent_deploy,
    _has_executable_sql,
    _split_sql_statements,
    validate_target_ddl,
)

# -- helpers --------------------------------------------------------------------
def _existing(cols):
    return {"exists": True, "columns": cols, "column_names": {c["name"] for c in cols}}

def _meta(schema_exists, tables):
    return {"schema_exists": schema_exists, "schema_name": "test_schema", "tables": tables}

def _find_col(cols, name):
    return next((c for c in cols if c["name"] == name), None)

def _cols_from_obj(obj):
    return [{"name": c["name"], "data_type": c["data_type"], "is_nullable": True}
            for c in obj["columns"]]

# ------------------------------------------------------------------------------
# TEST 1 — Simple columns: BIGINT, VARCHAR(100)
# ------------------------------------------------------------------------------
def test_1_simple_columns():
    ddl = """
    CREATE TABLE schema1.simple (
        id   BIGINT,
        name VARCHAR(100)
    );
    """
    req = _parse_required_objects_from_ddl(ddl)
    assert len(req) == 1, f"Expected 1 table, got {len(req)}"
    cols = req[0]["columns"]
    names = {c["name"] for c in cols}
    assert "id" in names and "name" in names, f"Missing cols: {names}"
    id_col = _find_col(cols, "id")
    assert "bigint" in id_col["data_type"].lower(), f"id type: {id_col['data_type']}"
    name_col = _find_col(cols, "name")
    assert "varchar" in name_col["data_type"].lower() or "character" in name_col["data_type"].lower(), \
        f"name type: {name_col['data_type']}"
    print("TEST 1 PASS — simple columns")

# ------------------------------------------------------------------------------
# TEST 2 — Identity column: BIGINT GENERATED BY DEFAULT AS IDENTITY
# ------------------------------------------------------------------------------
def test_2_identity_column():
    ddl = """
    CREATE TABLE schema1.with_identity (
        id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
        name TEXT NOT NULL
    );
    """
    req = _parse_required_objects_from_ddl(ddl)
    assert len(req) == 1
    cols = req[0]["columns"]
    id_col = _find_col(cols, "id")
    assert id_col is not None, "id column not found"
    assert id_col["is_identity"] is True, f"Expected is_identity=True: {id_col}"
    assert id_col["is_generated"] is True, f"Expected is_generated=True: {id_col}"
    # full_definition must include the complete GENERATED clause
    assert "GENERATED" in id_col["full_definition"].upper(), \
        f"full_definition missing GENERATED: {id_col['full_definition']}"
    assert "IDENTITY" in id_col["full_definition"].upper(), \
        f"full_definition missing IDENTITY: {id_col['full_definition']}"
    # data_type (for comparison) should be just BIGINT
    assert "bigint" in id_col["data_type"].lower(), f"data_type: {id_col['data_type']}"
    print("TEST 2 PASS — identity column parsed correctly")

# ------------------------------------------------------------------------------
# TEST 3 — Generated stored column: NUMERIC GENERATED ALWAYS AS (...) STORED
# ------------------------------------------------------------------------------
def test_3_generated_stored_column():
    ddl = """
    CREATE TABLE schema1.with_generated (
        price     NUMERIC(10,2),
        qty       INTEGER,
        total     NUMERIC GENERATED ALWAYS AS (price * qty) STORED
    );
    """
    req = _parse_required_objects_from_ddl(ddl)
    assert len(req) == 1
    cols = req[0]["columns"]
    total_col = _find_col(cols, "total")
    assert total_col is not None, "total column not found"
    assert total_col["is_generated"] is True
    assert "GENERATED ALWAYS AS" in total_col["full_definition"].upper()
    assert "STORED" in total_col["full_definition"].upper()
    # ALTER for generated STORED columns must be marked unsafe
    results = _build_alter_statements("s", "t", [total_col], "postgresql")
    assert len(results) == 1
    stmt, is_safe, reason = results[0]
    assert not is_safe, f"Generated-stored ALTER should be unsafe: {stmt}"
    assert "UNSAFE" in stmt.upper() or "cannot" in reason.lower()
    print("TEST 3 PASS — generated stored column: unsafe ALTER flagged")

# ------------------------------------------------------------------------------
# TEST 4 — DEFAULT expression: TIMESTAMP DEFAULT CURRENT_TIMESTAMP
# ------------------------------------------------------------------------------
def test_4_default_expression():
    ddl = """
    CREATE TABLE schema1.with_default (
        id         SERIAL PRIMARY KEY,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        label      VARCHAR(64) DEFAULT 'unknown'
    );
    """
    req = _parse_required_objects_from_ddl(ddl)
    cols = req[0]["columns"]
    names = {c["name"] for c in cols}
    # id comes from SERIAL — still a column
    assert "created_at" in names and "label" in names, f"Missing cols in: {names}"
    ca = _find_col(cols, "created_at")
    assert "timestamp" in ca["data_type"].lower(), f"created_at type: {ca['data_type']}"
    # full_definition must preserve DEFAULT clause
    assert "DEFAULT" in ca["full_definition"].upper(), \
        f"created_at full_def: {ca['full_definition']}"
    # ALTER statement must include the full_definition (including DEFAULT)
    results = _build_alter_statements("s", "t", [ca], "postgresql")
    stmt, is_safe, reason = results[0]
    assert is_safe, f"DEFAULT column ALTER should be safe: {reason}"
    assert "DEFAULT CURRENT_TIMESTAMP" in stmt.upper() or "DEFAULT" in stmt, \
        f"ALTER missing DEFAULT: {stmt}"
    print("TEST 4 PASS — DEFAULT expression preserved")

# ------------------------------------------------------------------------------
# TEST 5 — Nested function/expression containing commas
# ------------------------------------------------------------------------------
def test_5_nested_commas():
    ddl = """
    CREATE TABLE schema1.nested (
        amount NUMERIC(18, 2),
        ratio  NUMERIC(10, 4) DEFAULT 0.0,
        label  VARCHAR(100)
    );
    """
    req = _parse_required_objects_from_ddl(ddl)
    cols = req[0]["columns"]
    names = {c["name"] for c in cols}
    # All 3 columns must be parsed (commas inside parens must NOT split them)
    assert "amount" in names and "ratio" in names and "label" in names, \
        f"Missing columns in: {names}"
    amount = _find_col(cols, "amount")
    assert "numeric" in amount["data_type"].lower(), f"amount type: {amount['data_type']}"
    print("TEST 5 PASS — nested commas handled")

# ------------------------------------------------------------------------------
# TEST 6 — Constraints are NOT parsed as columns
# ------------------------------------------------------------------------------
def test_6_constraints_not_columns():
    ddl = """
    CREATE TABLE schema1.constrained (
        id     BIGINT NOT NULL,
        ref_id INTEGER NOT NULL,
        name   TEXT,
        PRIMARY KEY (id),
        UNIQUE (name),
        FOREIGN KEY (ref_id) REFERENCES other(id),
        CHECK (id > 0),
        CONSTRAINT uq_name UNIQUE (name)
    );
    """
    req = _parse_required_objects_from_ddl(ddl)
    cols = req[0]["columns"]
    names = [c["name"] for c in cols]
    # Only id, ref_id, name should appear
    assert "id" in names
    assert "ref_id" in names
    assert "name" in names
    # Constraints must NOT appear as columns
    for bad in ("primary", "unique", "foreign", "check", "constraint"):
        assert not any(bad in n.lower() for n in names), \
            f"Constraint keyword found as column name: {names}"
    assert len(cols) == 3, f"Expected 3 columns, got {len(cols)}: {names}"
    print("TEST 6 PASS — constraints excluded from column list")

# ------------------------------------------------------------------------------
# TEST 7 — Existing table missing a normal column ? valid ALTER generated
# ------------------------------------------------------------------------------
def test_7_alter_for_missing_column():
    ddl = """
    CREATE TABLE schema1.partial (
        id     BIGINT,
        name   TEXT,
        status VARCHAR(16)
    );
    """
    req = _parse_required_objects_from_ddl(ddl)
    # Simulate: id and name exist, status is missing
    existing_cols = [
        {"name": "id",   "data_type": "bigint",  "is_nullable": True},
        {"name": "name", "data_type": "text",    "is_nullable": True},
    ]
    tables = {"partial": _existing(existing_cols)}
    report = reconcile_objects(_meta(True, tables), req)
    assert report["counts"]["different"] == 1
    diff_obj = next(v for v in report["objects"].values() if v["status"] == "DIFFERENT")
    missing = diff_obj["missing_columns"]
    assert len(missing) == 1 and missing[0]["name"] == "status"
    results = _build_alter_statements("schema1", "partial", missing, "postgresql")
    assert len(results) == 1
    stmt, is_safe, reason = results[0]
    assert is_safe, f"Normal column ALTER should be safe: {reason}"
    assert "status" in stmt.lower()
    assert "varchar" in stmt.lower() or "character varying" in stmt.lower()
    # Must not contain incomplete fragment
    assert not re.search(r'\bVARCHAR\s*;', stmt, re.IGNORECASE), f"Incomplete ALTER: {stmt}"
    print("TEST 7 PASS — valid ALTER generated for missing normal column")

# ------------------------------------------------------------------------------
# TEST 8 — Missing generated column ? complete valid ALTER OR INVALID (no partial SQL)
# ------------------------------------------------------------------------------
def test_8_missing_generated_column():
    # identity column — PG supports ALTER ADD COLUMN ... GENERATED BY DEFAULT AS IDENTITY
    ddl = """
    CREATE TABLE schema1.with_identity2 (
        id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
        name TEXT
    );
    """
    req = _parse_required_objects_from_ddl(ddl)
    id_col = _find_col(req[0]["columns"], "id")
    results = _build_alter_statements("schema1", "with_identity2", [id_col], "postgresql")
    assert len(results) == 1
    stmt, is_safe, reason = results[0]
    if is_safe:
        # Must contain the complete GENERATED clause
        assert "GENERATED" in stmt.upper() and "IDENTITY" in stmt.upper(), \
            f"Incomplete identity ALTER: {stmt}"
        # Must NOT be a partial/truncated fragment
        assert not re.search(r'GENERATED\s*;', stmt, re.IGNORECASE), f"Truncated ALTER: {stmt}"
        assert not re.search(r'GENERATED\s+BY\s*;', stmt, re.IGNORECASE), f"Truncated ALTER: {stmt}"
    else:
        # If classified as unsafe, the reason must explain why (not just fail silently)
        assert reason and len(reason) > 5, f"Unsafe reason too vague: {reason}"

    # generated STORED column — must never produce valid ALTER (unsafe)
    ddl2 = """
    CREATE TABLE schema1.with_stored (
        price NUMERIC(10,2),
        total NUMERIC GENERATED ALWAYS AS (price * 1.1) STORED
    );
    """
    req2 = _parse_required_objects_from_ddl(ddl2)
    total_col = _find_col(req2[0]["columns"], "total")
    results2 = _build_alter_statements("schema1", "with_stored", [total_col], "postgresql")
    stmt2, is_safe2, reason2 = results2[0]
    assert not is_safe2, f"Stored-generated ALTER must be unsafe: {stmt2}"
    # The stmt must start with -- (comment) not with ALTER
    assert stmt2.startswith("--"), f"Unsafe stmt should be a comment: {stmt2}"
    print("TEST 8 PASS — generated column: complete valid ALTER or properly INVALID (no partial SQL)")

# ------------------------------------------------------------------------------
# TEST 9 — _is_alter_safe rejects incomplete fragments
# ------------------------------------------------------------------------------
def test_9_alter_safety_validator():
    # These must be REJECTED
    bad = [
        "ALTER TABLE s.t ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY;",
        "ALTER TABLE s.t ADD COLUMN IF NOT EXISTS id BIGINT GENERATED ALWAYS;",
        "ALTER TABLE s.t ADD COLUMN IF NOT EXISTS created_at DEFAULT;",
        "ALTER TABLE s.t ADD COLUMN IF NOT EXISTS name VARCHAR;",
        "ALTER TABLE s.t ADD COLUMN IF NOT EXISTS val NUMERIC;",
        "ALTER TABLE s.t ADD COLUMN IF NOT EXISTS val BIGINT",   # no semicolon
    ]
    for stmt in bad:
        safe, reason = _is_alter_safe(stmt)
        assert not safe, f"Should be UNSAFE: {stmt!r}"

    # These must be ACCEPTED
    good = [
        "ALTER TABLE s.t ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;",
        "ALTER TABLE s.t ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;",
        "ALTER TABLE s.t ADD COLUMN IF NOT EXISTS name VARCHAR(64);",
        "ALTER TABLE s.t ADD COLUMN IF NOT EXISTS amount NUMERIC(18,2);",
    ]
    for stmt in good:
        safe, reason = _is_alter_safe(stmt)
        assert safe, f"Should be SAFE: {stmt!r} — reason: {reason}"

    print("TEST 9 PASS — _is_alter_safe correctly validates/rejects ALTER statements")

# ------------------------------------------------------------------------------
# TEST 10 — Repeated deployment remains idempotent
# ------------------------------------------------------------------------------
def test_10_idempotent():
    ddl = """
    CREATE TABLE schema1.stable (
        id   BIGINT,
        val  NUMERIC(10,2),
        label TEXT
    );
    """
    req = _parse_required_objects_from_ddl(ddl)
    cols = [{"name": c["name"], "data_type": c["data_type"], "is_nullable": True} for c in req[0]["columns"]]
    tables = {"stable": _existing(cols)}
    r1 = reconcile_objects(_meta(True, tables), req)
    r2 = reconcile_objects(_meta(True, tables), req)
    assert r1["counts"] == r2["counts"]
    assert r1["counts"]["existing"] == 1
    assert r1["counts"]["missing"] == 0
    print("TEST 10 PASS — repeated reconciliation is idempotent")

# ------------------------------------------------------------------------------
# TEST 11 — Generic: works for any control ID (CTRL-N)
# ------------------------------------------------------------------------------
def test_11_cross_control_generic():
    for ctrl_n in [6, 23, 99, 112]:
        schema = f"ra_ctrl_{ctrl_n}"
        ddl = f"""
        CREATE TABLE IF NOT EXISTS {schema}.ctrl_stg_{ctrl_n} (
            run_id   INTEGER NOT NULL,
            val      NUMERIC(18,4),
            calc_ts  TIMESTAMP DEFAULT NOW()
        );
        """
        req = _parse_required_objects_from_ddl(ddl)
        assert len(req) == 1, f"ctrl_{ctrl_n}: expected 1 table"
        cols = req[0]["columns"]
        assert len(cols) == 3, f"ctrl_{ctrl_n}: expected 3 cols, got {len(cols)}: {[c['name'] for c in cols]}"
        # Sandbox deploy must succeed and mention the schema in stages
        cfg = {"db_type": "sandbox", "schema_name": schema}
        success, msg, recon, stages = idempotent_deploy(cfg, ddl, analysis_data={"ctrl_id_info": {"control_id": str(ctrl_n)}})
        assert success, f"ctrl_{ctrl_n}: deploy failed: {msg}"
        stage_text = " ".join(s["label"] for s in stages).lower()
        assert schema in stage_text, f"ctrl_{ctrl_n}: schema not in stages: {stage_text}"
        # No hardcoded control numbers from other controls (e.g. ctrl_23 hardcoded during ctrl_6 test)
        for s in stages:
            for other_n in [x for x in [6, 23, 99, 112] if x != ctrl_n]:
                assert not re.search(rf"ctrl[-_ ]{other_n}\b", s.get("label", "").lower()), \
                    f"hardcoded foreign control number {other_n} in stages for ctrl_{ctrl_n}: {s['label']}"
    print("TEST 11 PASS — generic across multiple control identifiers")

# ------------------------------------------------------------------------------
# TEST 12 — SQL Parser test cases (Cases 1-5 + Master Comments)
# ------------------------------------------------------------------------------
def test_12_sql_parser_cases():
    # CASE 1: -- comment only -> SKIP
    case1 = "-- comment only"
    assert not _has_executable_sql(case1), "Case 1 failed: comment only should not be executable"
    stmts1 = _split_sql_statements(case1)
    assert len(stmts1) == 0, f"Case 1 failed: expected 0 statements, got {len(stmts1)}"

    # CASE 2: -- comment \n CREATE TABLE test_table (id BIGINT); -> CREATE statement only
    case2 = """-- comment
    CREATE TABLE test_table (id BIGINT);"""
    assert _has_executable_sql(case2), "Case 2 failed: should have executable SQL"
    stmts2 = _split_sql_statements(case2)
    assert len(stmts2) == 1, f"Case 2 failed: expected 1 statement, got {len(stmts2)}"
    assert "CREATE TABLE test_table" in stmts2[0], f"Case 2 statement content mismatch: {stmts2[0]}"

    # CASE 3: DO $$ BEGIN PERFORM 1; END $$; -> ONE statement
    case3 = """DO $$
    BEGIN
        PERFORM 1;
    END $$;"""
    assert _has_executable_sql(case3), "Case 3 failed: DO block should be executable"
    stmts3 = _split_sql_statements(case3)
    assert len(stmts3) == 1, f"Case 3 failed: expected 1 statement, got {len(stmts3)}"
    assert "PERFORM 1" in stmts3[0], f"Case 3 content mismatch: {stmts3[0]}"

    # CASE 4: CREATE TABLE test (name VARCHAR(100), description TEXT DEFAULT 'abc;def'); -> ONE statement
    case4 = """CREATE TABLE test (
        name VARCHAR(100),
        description TEXT DEFAULT 'abc;def'
    );"""
    assert _has_executable_sql(case4), "Case 4 failed: CREATE table with semicolon in string"
    stmts4 = _split_sql_statements(case4)
    assert len(stmts4) == 1, f"Case 4 failed: expected 1 statement, got {len(stmts4)}"
    assert "'abc;def'" in stmts4[0], f"Case 4 content mismatch: {stmts4[0]}"

    # CASE 5: ALTER TABLE "ra_ctrl.ctrl_23".ctrl_config ADD COLUMN IF NOT EXISTS test_column TEXT;
    case5 = """ALTER TABLE "ra_ctrl.ctrl_23".ctrl_config
    ADD COLUMN IF NOT EXISTS test_column TEXT;"""
    assert _has_executable_sql(case5), "Case 5 failed: ALTER TABLE with quoted dot identifier"
    stmts5 = _split_sql_statements(case5)
    assert len(stmts5) == 1, f"Case 5 failed: expected 1 statement, got {len(stmts5)}"
    assert '"ra_ctrl.ctrl_23".ctrl_config' in stmts5[0]

    # CASE 6: DDL with master table comments (the exact trigger for psycopg2 empty query error)
    case6 = """-- ============================================================================
-- MASTER / REFERENCE TABLES (PRE-EXISTING IN TARGET SCHEMA — NOT CREATED)
-- Naming convention: ra_ctrl.ctrl_23.ctrl_23_<table_name>
-- e.g. "ra_ctrl.ctrl_23".ctrl_23_bucket_config
-- These tables exist in the target schema
"""
    assert not _has_executable_sql(case6), "Case 6 failed: master comments block must be non-executable"
    stmts6 = _split_sql_statements(case6)
    assert len(stmts6) == 0, f"Case 6 failed: expected 0 statements from master comments, got {len(stmts6)}"
    print("TEST 12 PASS — all SQL parser test cases verified (Cases 1-5 + Master Comments)")

# ------------------------------------------------------------------------------
# TEST 13 — Dry-run validation performs ZERO DDL execution
# ------------------------------------------------------------------------------
def test_13_dry_run_zero_ddl_execution():
    ddl = """-- ============================================================================
-- MASTER / REFERENCE TABLES (PRE-EXISTING IN TARGET SCHEMA — NOT CREATED)
-- Naming convention: ra_ctrl.ctrl_23.ctrl_23_<table_name>
-- e.g. "ra_ctrl.ctrl_23".ctrl_23_bucket_config
-- ============================================================================

CREATE TABLE IF NOT EXISTS "ra_ctrl.ctrl_23".ctrl_custom_table (
    id BIGINT,
    name VARCHAR(100)
);"""
    cfg = {"db_type": "sandbox", "schema_name": "ra_ctrl.ctrl_23"}
    success, msg, recon, stages = validate_target_ddl(cfg, ddl)
    assert success, f"Dry run validation failed: {msg}"
    assert "ctrl_custom_table" in recon["objects"]
    assert recon["objects"]["ctrl_custom_table"]["proposed_action"] == "CREATE TABLE"
    stage_labels = [s["label"] for s in stages]
    assert any("No database changes executed" in lbl for lbl in stage_labels), f"Missing no-change stage: {stage_labels}"
    print("TEST 13 PASS — dry-run validation verified with zero DDL execution")

# ------------------------------------------------------------------------------
# RUNNER
# ------------------------------------------------------------------------------
if __name__ == "__main__":
    tests = [
        test_1_simple_columns,
        test_2_identity_column,
        test_3_generated_stored_column,
        test_4_default_expression,
        test_5_nested_commas,
        test_6_constraints_not_columns,
        test_7_alter_for_missing_column,
        test_8_missing_generated_column,
        test_9_alter_safety_validator,
        test_10_idempotent,
        test_11_cross_control_generic,
        test_12_sql_parser_cases,
        test_13_dry_run_zero_ddl_execution,
    ]
    passed = failed = 0
    for t in tests:
        try:
            t(); passed += 1
        except Exception as e:
            import traceback
            print(f"FAIL {t.__name__}: {e}")
            traceback.print_exc()
            failed += 1
    print(f"\n{'='*50}")
    print(f"Results: {passed}/{len(tests)} passed, {failed} failed")
    sys.exit(1 if failed else 0)
