from sqlalchemy import create_engine, text

eng = create_engine('postgresql://hla_user:ganesh@13.127.198.137:5432/hla')
cfg_tables = [
    'cfg_internal_profiles_vdom',
    'cfg_managed_service_types',
    'cfg_test_dummy_ips',
    'cfg_internal_customer_exclusions'
]

with eng.begin() as conn:
    for t in cfg_tables:
        try:
            conn.execute(text(f'ALTER TABLE "ra_ctrl.ctrl_23".{t} ALTER COLUMN config_id ADD GENERATED BY DEFAULT AS IDENTITY;'))
            print(f"Added GENERATED BY DEFAULT AS IDENTITY to {t}")
        except Exception as e:
            print(f"Note on {t}: {e}")
