"""
Test Multi-Database & Cloud Dialect DDL, PK Definitions, and PySpark Pipelines
Covers: PostgreSQL, MSSQL, MySQL, Snowflake, Oracle, BigQuery
"""
import sys
import os

sys.stdout.reconfigure(encoding='utf-8')
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from target_logic_builder import (
    generate_target_ddl,
    generate_pyspark_pipeline,
    map_data_type,
    get_primary_key_column_def,
    _format_schema_prefix,
    ensure_target_tables_provisioned,
)
from db_fetcher import build_connection_url

def test_type_mappings():
    print("=== Testing Type Mappings Across Dialects ===")
    test_types = ["BIGINT", "VARCHAR(255)", "DATETIME", "DECIMAL(12,2)", "JSON", "BOOLEAN"]
    dialects = ["postgresql", "mssql", "mysql", "snowflake", "oracle", "bigquery"]

    for d in dialects:
        mapped = [f"{t} -> {map_data_type(t, d)}" for t in test_types]
        print(f"[{d.upper()}]: {', '.join(mapped[:3])}")
    print("✅ Type mappings passed.")

def test_pk_definitions():
    print("\n=== Testing Primary Key Column Definitions ===")
    dialects_expected = {
        "postgresql": 'GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
        "mssql": '[recon_id] BIGINT IDENTITY(1,1) PRIMARY KEY',
        "mysql": '`recon_id` BIGINT AUTO_INCREMENT PRIMARY KEY',
        "snowflake": '"recon_id" NUMBER(38,0) AUTOINCREMENT PRIMARY KEY',
        "oracle": '"RECON_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
    }

    for d, expected_substr in dialects_expected.items():
        pk_def = get_primary_key_column_def("recon_id", d)
        assert expected_substr in pk_def, f"Failed for {d}: got '{pk_def}', expected '{expected_substr}'"
        print(f"[{d.upper()}] PK Def: {pk_def}")
    print("✅ PK definitions passed.")

def test_ddl_generation_multi_dialect():
    print("\n=== Testing Multi-Dialect DDL Generation ===")
    mock_sources = [{"table_name": "billing_events", "schema_name": "cdr"}]
    mock_rules = {
        "filter_rules": [{"rule_statement": "Filter on (account_id)", "data_stream": "billing_events"}],
        "reconciliation_flows": [{"rule_statement": "Match on account_id"}]
    }
    mock_mappings = [{"source_table": "billing_events", "source_field": "account_id", "target_column": "account_id"}]
    mock_introspected = {
        "billing_events": {
            "table_found": True,
            "columns": [
                {"name": "account_id", "type": "BIGINT", "is_primary_key": True},
                {"name": "charge_amt", "type": "DECIMAL(10,2)"},
                {"name": "event_timestamp", "type": "TIMESTAMP"}
            ]
        }
    }
    mock_analysis = {
        "control_overview": {"identification": {"control_number": "ctrl_test"}},
        "rules": mock_rules,
        "mappings": mock_mappings
    }

    dialects = ["postgresql", "mssql", "mysql", "snowflake", "oracle"]
    for d in dialects:
        ddl = generate_target_ddl(
            target_schema="ra_ctrl.ctrl_test",
            target_dialect=d,
            sources=mock_sources,
            rules=mock_rules,
            mappings=mock_mappings,
            introspected_schemas=mock_introspected,
            analysis_data=mock_analysis
        )
        assert len(ddl) > 100, f"Empty DDL generated for {d}"

        # Verify dialect specific quoting or keywords
        if d == "mssql":
            assert "IDENTITY(1,1)" in ddl, "MSSQL must use IDENTITY(1,1) syntax"
            assert "[match_id]" in ddl, "MSSQL must quote column with brackets"
        elif d == "mysql":
            assert "AUTO_INCREMENT" in ddl, "MySQL must use AUTO_INCREMENT"
            assert "`match_id`" in ddl, "MySQL must quote column with backticks"
        elif d == "snowflake":
            assert "AUTOINCREMENT" in ddl, "Snowflake must use AUTOINCREMENT"
            assert "CREATE SCHEMA IF NOT EXISTS" in ddl
        elif d == "oracle":
            assert "VARCHAR2" in ddl, "Oracle must map VARCHAR to VARCHAR2"

        print(f"[{d.upper()}] Generated {len(ddl.splitlines())} lines of DDL successfully.")
    print("✅ Multi-dialect DDL generation verified.")

def test_pyspark_pipeline_generation():
    print("\n=== Testing PySpark Pipeline Generation for Multi-Cloud DB Targets ===")
    mock_sources = [
        {
            "table_name": "billing_events",
            "schema_name": "cdr",
        },
        {
            "table_name": "sql_subscribers",
            "schema_name": "crm",
        }
    ]
    mock_rules = {"reconciliation_flows": [{"rule_statement": "Match msisdn"}]}
    mock_mappings = [{"source_table": "billing_events", "source_field": "msisdn", "target_column": "msisdn"}]

    # Test PySpark with MSSQL target
    spark_code_mssql = generate_pyspark_pipeline(
        target_schema="ra_ctrl.ctrl_test",
        target_db_config={
            "db_type": "mssql",
            "host": "sqlserver.corp.local",
            "port": 1433,
            "database_name": "telecom_warehouse",
            "schema_name": "recon_target",
            "username": "sa"
        },
        sources=mock_sources,
        rules=mock_rules,
        mappings=mock_mappings,
        control_overview={"identification": {"control_number": "ctrl_test"}}
    )

    assert "com.microsoft.sqlserver.jdbc.SQLServerDriver" in spark_code_mssql, "Should use MSSQL JDBC driver"
    assert "jdbc:sqlserver://sqlserver.corp.local:1433;databaseName=telecom_warehouse" in spark_code_mssql
    print("✅ PySpark MSSQL target pipeline generated successfully.")

    # Test PySpark with Snowflake target
    spark_code_sf = generate_pyspark_pipeline(
        target_schema="ANALYTICS",
        target_db_config={
            "db_type": "snowflake",
            "host": "xy12345.snowflakecomputing.com",
            "database_name": "FIN_DB",
            "schema_name": "ANALYTICS",
            "username": "ETL_USER"
        },
        sources=mock_sources,
        rules=mock_rules,
        mappings=mock_mappings,
        control_overview={"identification": {"control_number": "ctrl_test"}}
    )
    assert 'net.snowflake.client.jdbc.SnowflakeDriver' in spark_code_sf, "Should use Snowflake JDBC driver"
    print("✅ PySpark Snowflake target pipeline generated successfully.")

def test_connection_url_building():
    print("\n=== Testing Connection URL Building for Cloud DBs & Warehouses ===")
    configs = [
        ({"db_type": "postgresql", "host": "localhost", "port": 5432, "database_name": "hla_db", "username": "pg", "password": "pwd"}, "postgresql"),
        ({"db_type": "mysql", "host": "mysql.cloud.io", "port": 3306, "database_name": "shop", "username": "root", "password": "pwd"}, "mysql+pymysql://root:pwd@mysql.cloud.io:3306/shop"),
        ({"db_type": "mssql", "host": "mssql.windows.net", "port": 1433, "database_name": "azuredb", "username": "admin", "password": "pwd"}, "mssql+pyodbc://admin:pwd@mssql.windows.net:1433/azuredb"),
        ({"db_type": "snowflake", "host": "xy12345.snowflakecomputing.com", "port": "FIN_WH", "database_name": "DATA_WH", "schema_name": "PUBLIC", "username": "analyst", "password": "pwd"}, "snowflake://analyst:pwd@xy12345/DATA_WH/PUBLIC?warehouse=FIN_WH"),
    ]

    for cfg, expected_prefix in configs:
        url = build_connection_url(cfg)
        assert url.startswith(expected_prefix), f"Failed for {cfg['db_type']}: got {url}, expected prefix {expected_prefix}"
        print(f"[{cfg['db_type'].upper()} URL]: {url[:45]}...")
    print("✅ Connection URLs validated.")

if __name__ == '__main__':
    test_type_mappings()
    test_pk_definitions()
    test_ddl_generation_multi_dialect()
    test_pyspark_pipeline_generation()
    test_connection_url_building()
    print("\n🎉 ALL MULTI-DATABASE & CLOUD TESTS PASSED PERFECTION!")
